name: ML Workflow

on:
  push:
    branches:
      - cicd-tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.9

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
        shell: bash

      - name: Install dependencies
        run: |
          poetry install
        working-directory: .

      - name: Run Pytest
        run: |
          poetry run pytest
        working-directory: .
